@startuml

title __TEMP's Class Diagram__\n

  namespace temp {
    class temp.Main {
        {static} + main()
        + onUDPHolePanchingFinish()
        - start()
    }
  }
  

  namespace temp {
    interface temp.UDPHolePanchingFinishListener {
        {abstract} + onUDPHolePanchingFinish()
    }
  }
  

  namespace temp {
    class temp.UDPHolePunchingServer {
        {static} ~ SERVER_PORT : int
        - serverSocket : DatagramSocket
        + onReceiveMsg()
        + onSendFinishMsg()
        + run()
        ~ UDPHolePunchingServer()
        - startUDPHoleServerSend()
    }
  }
  

  namespace temp {
    class temp.UDPHolePunchingServerReceive {
        ~ datagramSocket : DatagramSocket
        + run()
        ~ UDPHolePunchingServerReceive()
    }
  }
  

  namespace temp {
    interface temp.UDPHolePunchingServerReceiveListener {
        {abstract} + onReceiveMsg()
    }
  }
  

  namespace temp {
    class temp.UDPHolePunchingServerSend {
        - IPAddress : InetAddress
        - datagramSocket : DatagramSocket
        - port : int
        + run()
        ~ UDPHolePunchingServerSend()
        - sleep()
    }
  }
  

  namespace temp {
    interface temp.UDPHolePunchingServerSendListener {
        {abstract} + onSendFinishMsg()
    }
  }
  

  temp.Main .up.|> temp.UDPHolePanchingFinishListener
  temp.UDPHolePunchingServer .up.|> temp.UDPHolePunchingServerReceiveListener
  temp.UDPHolePunchingServer .up.|> temp.UDPHolePunchingServerSendListener
  temp.UDPHolePunchingServer o-- temp.UDPHolePanchingFinishListener : udpHolePanchingFinishListener
  temp.UDPHolePunchingServerReceive o-- temp.UDPHolePunchingServerReceiveListener : udpHolePunchingServerReceiveListener
  temp.UDPHolePunchingServerSend o-- temp.UDPHolePunchingServerSendListener : udpHolePunchingServerSendListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
